const quotes = {
  happy: [
    "Happiness looks gorgeous on you.",
    "Aaj toh smile contagious hogi!",
    "Joy is your natural state.",
    "Khushi koi destination nahi, ek vibe hai.",
    "Small moments, big smiles.",
    "Laugh more, worry less.",
    "You deserve this happiness.",
    "Sunshine suits your soul.",
    "Today feels lighter already.",
    "Khud pe muskura lena bhi jeet hai.",
    "Happiness begins with gratitude.",
    "Tumhari energy bright hai.",
    "Good vibes only, always.",
    "Smile — it's free therapy.",
    "Khushi loud nahi hoti, real hoti hai.",
    "Life feels kinder today.",
    "Dil halka hai aaj.",
    "Joy chooses you today.",
    "Celebrate nothing — that's happiness.",
    "You glow differently when happy.",
    "Aaj dil ka weather clear hai.",
    "Pure joy, no filters.",
    "Tumhari smile ka jawab nahi.",
    "Happiness found you.",
    "Sukoon mode ON.",
    "Aaj sab theek lag raha hai.",
    "Heart feels warm.",
    "Khushi ka reason mat dhoondh.",
    "Life feels good.",
    "Bas khush rehne ka mann hai."
  ],

  sad: [
    "It's okay to not be okay.",
    "Aaj heavy lag raha hai, samajh sakta hoon.",
    "Crying is not weakness.",
    "This feeling will pass.",
    "Tum akela nahi ho.",
    "Pain teaches silently.",
    "Slow days are allowed.",
    "Healing takes time.",
    "Dil thak gaya hai, par tuta nahi.",
    "Sadness doesn't define you.",
    "Tomorrow can be softer.",
    "Let yourself feel.",
    "Dark phases make stars visible.",
    "Thoda rukna bhi zaroori hai.",
    "You're allowed to rest.",
    "Even storms end.",
    "Dard bolta nahi, mehsoos hota hai.",
    "Be gentle with yourself.",
    "You matter — even now.",
    "Tears clean the soul.",
    "This is not the end.",
    "Heart needs patience.",
    "Sad ≠ weak.",
    "You're still worthy.",
    "Heavy hearts still beat.",
    "Aaj thoda kamzor feel karna theek hai.",
    "Hope is resting, not gone.",
    "Feel it, don't fight it.",
    "Tomorrow is trying.",
    "You'll smile again."
  ],

  stressed: [
    "Breathe. You got this.",
    "One thing at a time.",
    "Pause ≠ quit.",
    "You're not behind.",
    "Slow progress is still progress.",
    "Stress is loud, calm is stronger.",
    "Relax your shoulders.",
    "Not everything needs fixing now.",
    "Tum sirf insaan ho.",
    "Overthinking won't solve it.",
    "Rest is productive.",
    "You've survived worse.",
    "Deep breath, reset.",
    "Pressure doesn't define capability.",
    "It's okay to log off.",
    "Mind needs silence too.",
    "Calm yourself first.",
    "Control what you can.",
    "Stress doesn't mean failure.",
    "Step back to move forward.",
    "Tum kaafi ho.",
    "Slow down, warrior.",
    "Chaos will settle.",
    "You're doing enough.",
    "Don't rush healing.",
    "Still breathing = winning.",
    "Release the tension.",
    "This too shall pass.",
    "Trust yourself.",
    "Peace over perfection."
  ],

  angry: [
    "Pause before reacting.",
    "Silence is powerful.",
    "Anger hides pain.",
    "Choose calm.",
    "Don't let anger drive.",
    "Your peace matters.",
    "Step away, breathe.",
    "Anger fades, damage stays.",
    "Respond, don't explode.",
    "Control gives power.",
    "You're bigger than this.",
    "Calm is strength.",
    "Release, don't suppress.",
    "Anger is temporary.",
    "Don't burn bridges.",
    "Protect your energy.",
    "Peace is a choice.",
    "Anger drains you.",
    "Slow breaths help.",
    "Step back.",
    "You deserve calm.",
    "Let go.",
    "This moment will pass.",
    "Choose peace.",
    "Be still.",
    "Think twice.",
    "Your future self is watching.",
    "Don't react instantly.",
    "Calm mind wins.",
    "Anger isn't truth."
  ],

  neutral: [
    "Every moment is a fresh beginning.",
    "You are doing great!",
    "Just be present.",
    "Today is neutral — and that's okay.",
    "Nothing urgent right now.",
    "Balance feels good.",
    "No rush.",
    "Simple moments matter.",
    "You exist, that's enough.",
    "Middle days count too.",
    "Not every day is extreme.",
    "Calm baseline.",
    "Steady is powerful.",
    "Being okay is success.",
    "No pressure today.",
    "Just flow.",
    "Neutral days recharge.",
    "You're aligned.",
    "Stillness is fine.",
    "Not good, not bad — alive.",
    "This moment just is.",
    "Breathing, existing.",
    "No expectations.",
    "Centered.",
    "Grounded.",
    "Neutral doesn't mean empty.",
    "Balance achieved.",
    "Clarity comes here.",
    "Stable is strong.",
    "You're okay."
  ],

  motivational: [
    "Start before you're ready.",
    "Consistency beats motivation.",
    "Do it scared.",
    "Future you is watching.",
    "One step today.",
    "No excuses, just progress.",
    "Discipline > mood.",
    "Dreams need action.",
    "You are capable.",
    "Keep moving.",
    "Small wins matter.",
    "Don't stop now.",
    "You've come far.",
    "Focus beats talent.",
    "Hard days build strength.",
    "Level up daily.",
    "Comfort kills growth.",
    "Push through.",
    "Results take time.",
    "Trust the grind.",
    "You owe yourself success.",
    "Stay hungry.",
    "Work silently.",
    "Make yourself proud.",
    "One more try.",
    "No shortcuts.",
    "You're unstoppable.",
    "Eyes on the goal.",
    "Earn it.",
    "Rise again."
  ]
};

module.exports = quotes;
